import diffusion_processes_stochastic_analysis_manifolds_theorem_canonical_lane_mathlib.GateLemmas
namespace HautevilleHouse
namespace diffusion_processes_stochastic_analysis_manifolds_theorem_canonical_lane_mathlib
structure ConstrainedTheoremClosure where
  admissible :: intro :: constraint :: consequence :: proof ::
theorem canonical : ConstrainedTheoremClosure :=
  ConstrainedTheoremClosure.intro
end diffusion_processes_stochastic_analysis_manifolds_theorem_canonical_lane_mathlib
end HautevilleHouse
